# -*- coding: utf-8 -*-
"""extract links for image_final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xr5DVmoKR_NdUtbshvLmo5Vj_VlhHIyj
"""

!sudo apt install tesseract-ocr
!pip install pytesseract

import pytesseract
import shutil
import os
import random
try:
 from PIL import Image
except ImportError:
 import Image

import regex as re

image_path_in_colab='img.jpg'
extractedInformation = pytesseract.image_to_string(Image.open(image_path_in_colab))
print(extractedInformation)
#slices_0= extractedInformation.slice()
#for slice_0 in slices_0{}

urls = re.findall('(?:(?:https?|ftp):\/\/)?[\w/\-?=%.]+\.[\w/\-&?=%.]+', extractedInformation)
print(urls)